#! /home/voccer/anaconda3/bin/python

import datetime
from lunarcalendar import Converter, Solar, Lunar
import requests
import subprocess
import shutil
import os

DIR_PATH = '/usr/games/notify_birthday'

## remove file exist
try:
    os.remove(os.path.join(DIR_PATH, 'index.html'))
    os.remove(os.path.join(DIR_PATH, 'result'))
except:
    pass


info = []
def set_info():
    with open(os.path.join(DIR_PATH,'birthday'), 'r') as f:
        p = f.read()
        p = p.split('\n')

    
    solar_today = datetime.date.today()

    lunar_today = Converter.Solar2Lunar(Solar(solar_today.year, solar_today.month, solar_today.day))

    for i in p:
        if i == '':
            continue
        name_birthday = i.split(':')[0]
        solar_birthday = i.split(':')[1].replace(' ', '')
        solar_day = int(solar_birthday.split('/')[0])
        solar_month = int(solar_birthday.split('/')[1])
        solar_year = int(solar_birthday.split('/')[2])
        lunar_birthday = Converter.Solar2Lunar(Solar(solar_year, solar_month, solar_day))


        if solar_day == solar_today.day and solar_month == solar_today.month:
            age = int(solar_today.year - solar_year)
            info.append([age, name_birthday, 'solar'])
        if lunar_birthday.day == lunar_today.day and lunar_birthday.month == lunar_today.month:
            age = int(lunar_today.year - lunar_birthday.year)
            info.append([age, name_birthday, 'lunar'])
    
    
set_info()

if len(info) > 0:
    with open(os.path.join(DIR_PATH,'result'), 'w') as f:
        for p in info:
            f.write(p[1])
    with open(os.path.join(DIR_PATH, 'index.html'), 'w') as index:
        with open(os.path.join(DIR_PATH, 'header.html'), 'r') as header:
            for l in header:
                index.write(l)

        for p in info:
            index.write('Today is {} birthday, {} age, {}<br>'.format(p[1].replace('\ufeff', ''), p[0], p[2]))

        with open(os.path.join(DIR_PATH, 'footer.html'), 'r') as footer:
            for l in footer:
                index.write(l)

    subprocess.run('node ' + os.path.join(DIR_PATH, 'script.js'), shell=True)

else:
    with open(os.path.join(DIR_PATH, 'result'), 'w') as f:
        for p in info:
            f.write('no thing')


# import time
# time.sleep(400)


try:
    r = requests.get('https://docs.google.com/document/u/0/export?format=txt&id=1b2aQMfZvhLhqs5bnGrdNZUnOSmCGsuNZeSH8Qk6ndrg&token=AC4w5VjlljBzAvNU8CtCSnvvFwe52p-2-w%3A1589941528767&ouid=102939292131381354747&includes_info_params=true&inspectorResult=%7B%22pc%22%3A1%2C%22lplc%22%3A20%7D')
    b = r.text
    with open(os.path.join(DIR_PATH,'birthday'), 'w') as f:
            f.write(b)
except Exception as e:
    print(e)